import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        "surface-bright": "#f9f9f9",
        "surface-container-low": "#f3f3f3",
        outline: "#747878",
        "inverse-surface": "#2f3131",
        "on-secondary-fixed": "#360f00",
        surface: "#f9f9f9",
        "surface-tint": "#5f5e5e",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#997f61",
        "secondary-fixed": "#ffdbcd",
        "surface-dim": "#dadada",
        "on-tertiary-fixed": "#281803",
        "on-primary-container": "#858383",
        "secondary-container": "#fdb293",
        "error-container": "#ffdad6",
        "primary-fixed": "#e5e2e1",
        "surface-container": "#eeeeee",
        "on-background": "#1a1c1c",
        "surface-container-highest": "#e2e2e2",
        "surface-container-high": "#e8e8e8",
        "primary-container": "#1c1b1b",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f0f1f1",
        tertiary: "#000000",
        "tertiary-container": "#281803",
        error: "#ba1a1a",
        "tertiary-fixed-dim": "#e0c29f",
        secondary: "#895037",
        "inverse-primary": "#c8c6c5",
        "on-error-container": "#93000a",
        "surface-variant": "#e2e2e2",
        "secondary-fixed-dim": "#ffb597",
        "on-surface-variant": "#444748",
        "on-primary-fixed-variant": "#474746",
        primary: "#000000",
        "on-secondary-fixed-variant": "#6c3922",
        "on-primary": "#ffffff",
        "on-surface": "#1a1c1c",
        "on-secondary-container": "#78422a",
        "on-primary-fixed": "#1c1b1b",
        "primary-fixed-dim": "#c8c6c5",
        "outline-variant": "#c4c7c7",
        "on-tertiary-fixed-variant": "#584329",
        "on-error": "#ffffff",
        "tertiary-fixed": "#fdddb9",
        "on-tertiary": "#ffffff",
        background: "#f9f9f9",
        foreground: "#1a1c1c",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-edge": "64px",
        "section-gap": "128px",
        gutter: "32px",
        unit: "8px",
        "container-max": "1440px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      height: {
        "section-gap": "128px",
      },
      fontFamily: {
        "headline-lg": ["Newsreader", "serif"],
        "label-caps": ["Inter", "sans-serif"],
        "display-xl": ["Newsreader", "serif"],
        "headline-md": ["Newsreader", "serif"],
        "technical-data": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        serif: ["Newsreader", "serif"],
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "display-xl": ["80px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "300" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
        "technical-data": ["13px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
